name: clean releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  actions: read

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: clean releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          
          threshold=$(date -d "90 days ago" +%s)
          
          gh release list --json tagName,createdAt,isDraft --limit 100 \
          | jq -r --argjson threshold "$threshold" '
              .[] | 
              select(
                ((.createdAt | fromdateiso8601) < $threshold or .isDraft == true) and
                .tagName != "" and
                .tagName != null and
                (.tagName | type == "string") and
                (.tagName | test("^(?!protected-).*$"))
              ) | 
              .tagName
          ' \
          | while IFS= read -r tag; do
              if [ -n "$tag" ]; then
                for attempt in {1..3}; do
                  if git tag --list "$tag" | grep -q "^$tag$"; then
                    timeout 10s bash -c "gh release delete \"$tag\" --yes && git tag -d \"$tag\" && git push origin --delete refs/tags/\"$tag\"" && {
                      break
                    } || {
                      if [ $attempt -lt 3 ]; then
                        sleep 2
                      fi
                    }
                  else
                    timeout 10s gh release delete "$tag" --yes && {
                      break
                    } || {
                      if [ $attempt -lt 3 ]; then
                        sleep 2
                      fi
                    }
                  fi
                done
              fi
            done

      - name: delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1