name: clean releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  actions: read

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: clean releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          
          threshold=$(date -d "90 days ago" +%s)
          
          gh release list --json tagName,createdAt,isDraft \
          | jq -r --argjson threshold "$threshold" '
              .[] | 
              select(
                ((.createdAt | fromdateiso8601) < $threshold or .isDraft == true) and
                .tagName != "" and
                .tagName != null
              ) | 
              .tagName
          ' \
          | while IFS= read -r tag; do
              if [ -n "$tag" ]; then
                echo "尝试删除 Release 和可能的 Tag: $tag"
                for attempt in {1..3}; do
                  if git tag --list "$tag" | grep -q "^$tag$"; then
                    # 标签存在，删除 Release 和 Tag
                    timeout 10s bash -c "gh release delete \"$tag\" --yes && git tag -d \"$tag\" && git push origin --delete refs/tags/\"$tag\"" && {
                      echo "成功删除 Release 和 Tag: $tag"
                      break
                    } || {
                      echo "尝试 $attempt 失败: $tag"
                      if [ $attempt -lt 3 ]; then
                        sleep 2
                        echo "重试 ($attempt/3)..."
                      else
                        echo "删除 Release 和 Tag $tag 失败，已达最大重试次数"
                      fi
                    }
                  else
                    timeout 10s gh release delete "$tag" --yes && {
                      echo "成功删除 Release（无对应 Tag）: $tag"
                      break
                    } || {
                      echo "尝试 $attempt 失败: $tag"
                      if [ $attempt -lt 3 ]; then
                        sleep 2
                        echo "重试 ($attempt/3)..."
                      else
                        echo "删除 Release $tag 失败，已达最大重试次数"
                      fi
                    }
                  fi
                done
              else
                echo "跳过空标签"
              fi
            done

      - name: delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1